apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: appdirect

spec:
  replicas: 2

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service
          image: 363518211010.dkr.ecr.ap-southeast-2.amazonaws.com/appdirect-order:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
