
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: appdirect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 363518211010.dkr.ecr.ap-southeast-2.amazonaws.com/appdirect-product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
