apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: appdirect

spec:
  selector:
    app: product-service

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP
